name: "Copilot Setup Steps"

on: push

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Setting up Copilot steps..."